FROM node:22-alpine AS builder
WORKDIR /app

ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY ./src ./src
COPY index.html vite.config.ts tsconfig.json tsconfig.app.json tsconfig.node.json ./

RUN pnpm build

FROM nginx:alpine AS runner

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]